export const fakeLatestData = [
  {
    caption: 'In Re: Risperdal Litig., Appeal of: Winter, J. (Pa. 2019)',
    dateFiled: 'November 19, 2019',
    docketNumber: '23 EAP 2018',
    link: '#',
    natureSuit: '',
    status: 'Precedential',
  },
  {
    caption: 'In Re: Risperdal Litig., Appeal of: Winter, J. (Pa. 2019)',
    dateFiled: 'November 19, 2019',
    docketNumber: '23 EAP 2018',
    link: '#',
    natureSuit: '',
    status: 'Precedential',
  },
  {
    caption: 'In Re: Risperdal Litig., Appeal of: Winter, J. (Pa. 2019)',
    dateFiled: 'November 19, 2019',
    docketNumber: '23 EAP 2018',
    link: '#',
    natureSuit: '',
    status: 'Precedential',
  },
  {
    caption: 'In Re: Risperdal Litig., Appeal of: Winter, J. (Pa. 2019)',
    dateFiled: 'November 19, 2019',
    docketNumber: '23 EAP 2018',
    link: '#',
    natureSuit: '',
    status: 'Precedential',
  },
  {
    caption: 'In Re: Risperdal Litig., Appeal of: Winter, J. (Pa. 2019)',
    dateFiled: 'November 19, 2019',
    docketNumber: '23 EAP 2018',
    link: '#',
    natureSuit: '',
    status: 'Precedential',
  },
  {
    caption: 'In Re: Risperdal Litig., Appeal of: Winter, J. (Pa. 2019)',
    dateFiled: 'November 19, 2019',
    docketNumber: '23 EAP 2018',
    link: '#',
    natureSuit: '',
    status: 'Precedential',
  },
]
export const fakeAudioData = [
  {
    caption: 'In Re: Risperdal Litig., Appeal of: Winter, J. (Pa. 2019)',
    dateArgued: 'November 19, 2019',
    docketNumber: '23 EAP 2018',
    duration: '45:33',
    link: '#',
  },
  {
    caption: 'In Re: Risperdal Litig., Appeal of: Winter, J. (Pa. 2019)',
    dateArgued: 'November 19, 2019',
    docketNumber: '23 EAP 2018',
    duration: '45:33',
    link: '#',
  },
  {
    caption: 'In Re: Risperdal Litig., Appeal of: Winter, J. (Pa. 2019)',
    dateArgued: 'November 19, 2019',
    docketNumber: '23 EAP 2018',
    duration: '45:33',
    link: '#',
  },
  {
    caption: 'In Re: Risperdal Litig., Appeal of: Winter, J. (Pa. 2019)',
    dateArgued: 'November 19, 2019',
    docketNumber: '23 EAP 2018',
    duration: '45:33',
    link: '#',
  },
  {
    caption: 'In Re: Risperdal Litig., Appeal of: Winter, J. (Pa. 2019)',
    dateArgued: 'November 19, 2019',
    docketNumber: '23 EAP 2018',
    duration: '45:33',
    link: '#',
  },
  {
    caption: 'In Re: Risperdal Litig., Appeal of: Winter, J. (Pa. 2019)',
    dateArgued: 'November 19, 2019',
    docketNumber: '23 EAP 2018',
    duration: '45:33',
    link: '#',
  },
]
